#!/bin/bash
## reverse-string
## version 0.0.1 - initial
##################################################
seq() { { local ubound ; ubound="${1}" ; }
  local i
  for i in $( eval echo {1..${ubound}} )
  do
   echo ${i}
  done
}
reverse-string() { { local instr ; instr="${1}" ; }
  for i in $( seq ${#instr} )
  do
   echo -n ${instr:$(( ${#instr} - ${i} )):1}
  done
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
reverse-string ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 22 Oct 2019 13:46:15 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
